### ISSUE TITLE
安全防护软件提示: 端口扫描攻击，什么原因？

### ISSUE THREAD

**Issue by MrBenWang** [nobody3u/V2RayGCon#10]
1、安全防护软件提示: 端口扫描攻击，什么原因？如下图
2、是客户端的原因，还是v2ray core的原因？

公司电脑，麻烦看一下不能关闭防护软件。

![githubbug](https://user-images.githubusercontent.com/9692054/45744846-0e5a8480-bc32-11e8-8d42-c67d19ea1d29.jpg)

**Comment by nobody3u** [comment]
这我也不太清楚什么引起，不过可以用逐步排查。
先进入v2ray-core的目录直接双击v2ray.exe。
如果还有这个提示，那基本是Symantec的锅。

**Comment by MrBenWang** [comment]
我看了下服务端的日志 access.log  , 认为应该是 core的原因。我去那边提一下

```
2018/09/19 17:27:37 ***.***.***.***:11406 accepted tcp:www.google.com:443
2018/09/19 17:28:56 ***.***.***.***:11475 accepted tcp:www.google.com:443
2018/09/19 17:30:28 ***.***.***.***:11553 accepted tcp:www.google.com:443
2018/09/19 17:30:29 ***.***.***.***:11555 accepted udp:1.1.1.1:53
2018/09/19 17:30:30 ***.***.***.***:11556 accepted tcp:www.google.com:443
```

另外，我建议 zip 包里面，最好去掉 *.pdb   *.xml  这些开发的文件。
还有个小BUG，vmess信息填写完后。  
先点击 Stream Settings 的【插入】  ，会清空VMess 框里面的信息。
![_20180919194601](https://user-images.githubusercontent.com/9692054/45753683-2d661000-bc4c-11e8-8821-5ab42254ee7f.jpg)

**Comment by nobody3u** [comment]
不大可能是core的问题，这个日志看着像是在并行进行多个速度测试。
每个测速的服务器都会占用一个端口，可能用的端口太多触发了防火墙规则。
试下 `更多...`-`速度测试` 只对一单个服务器测速，看会不会引发这个问题？

配置编辑器的清空问题只能说是by design了。
为了兼顾ss，所以vmess和streamSettings是分开两个部分。
不然ss那个面板又要做个重复的streamSettings。

**Comment by MrBenWang** [comment]
我今天测试了，可以确定是v2ray kcp 协议导致的。
