### ISSUE TITLE
能否加个PAC代理模式

### ISSUE THREAD

**Issue by winds365** [nobody3u/V2RayGCon#11]
前几天用了下V2RayGCon，感觉不错
但是，我不喜欢直接设为系统代理
会有好多不必要的流量走代理
能否加个PAC代理模式

**Comment by nobody3u** [comment]
可以通过以下两种方式分流：

#### 1.浏览器插件
比如chrome的SwitchyOmega
比如Firefox的FoxyProxy
IE好像不支持PAC，其他浏览器没怎么用不清楚
然后在插件里创建一个PAC情境模式
可以到网上找PAC或者到以下项目下载一份
https://nobody3u.github.io/VGCTools/#/pac

#### 2.使用这个软件提供的import功能
即在相应的服务器项中点 `更多...`-`编辑`
然后在右侧相应部分加入以下配置
```
{
  "v2raygcon": {
    "import": {
      "http://suo.im/5lp5PJ": "白名单模板",
    }
  }
  // 其他配置
}
```
接着点`服务器`-`保存当前配置`
import功能的详细介绍请看 [Import（导入模板）](https://github.com/nobody3u/V2RayGCon/wiki/Import%EF%BC%88%E5%AF%BC%E5%85%A5%E6%A8%A1%E6%9D%BF%EF%BC%89)

这个软件只是个纯粹的GUI，我不想在里面捆绑其他软件
所以没能像v2rayN那样通过privoxy提供PAC模式
