### ISSUE TITLE
能否支持pac？

### ISSUE THREAD

**Issue by Ramon403** [nobody3u/V2RayGCon#13]
设为系统代理，都是全局模式，能否支持Pac模式的？

**Comment by nobody3u** [comment]
请看 issue  #11 
 `v1.0.30` 新增加的`分流国内`选项（一会将在主窗口的wiki中加入说明）
以及 [小技巧-实现类似PAC的分流国内外流量效果](https://github.com/nobody3u/V2RayGCon/wiki/%E5%B0%8F%E6%8A%80%E5%B7%A7#%E5%AE%9E%E7%8E%B0%E7%B1%BB%E4%BC%BCpac%E7%9A%84%E5%88%86%E6%B5%81%E5%9B%BD%E5%86%85%E5%A4%96%E6%B5%81%E9%87%8F%E6%95%88%E6%9E%9C)

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
