### ISSUE TITLE
能否为多开设立一个标记？

### ISSUE THREAD

**Issue by redfrog999** [nobody3u/V2RayGCon#14]
如题，有多台服务器的情况下会无法辨识某台服务器是否多开了，像我的使用场景，分别设置了http和socks端口，反复测试多开还会导致软件闪退。希望下个版本能改进，非常感谢。

**Comment by redfrog999** [comment]
我理解你的多开逻辑是这样：
假如现在有1080，1081，1082三个端口，点击多开之后就直接开启这三个服务器端口了。

我想实现的功能是点击多开之后并不马上开启这个端口，因为我有30-40个服务器，有的可能现在能用，有的不能用，需要先测试一下，而且多个服务器会共用1081这个端口，所以想要把测试能用的那些服务器像分流和自启动那样做一个标识，以后我就可以快速选择哪些服务器可以自启动多开啦。

闪退出现前我的操作就是反复点击了好几个服务器的多开选项，因为我不知道哪些能现在联通用上，所以反复操作后就直接闪退了。

希望我表述清楚了。再次感谢。

**Comment by redfrog999** [comment]
按照你的逻辑更好选择了。非常感谢。

闪退出现就是在我多次开关多开选项之后，偶尔会出现。刚才再测试了几遍，又没有出现了。我再多测试看看，如有复现再来反馈。

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
