### ISSUE TITLE
二维码太小

### ISSUE THREAD

**Issue by ZeekoZhu** [nobody3u/V2RayGCon#17]
![image](https://user-images.githubusercontent.com/13861843/46200827-3be7b200-c345-11e8-9742-b515e542593d.png)

电脑是 MacBook Pro，屏幕分辨率是 2880x1800，已经在系统设置里面开启了 200% 缩放

**Comment by nobody3u** [comment]
添加了缩放选项，你可以试用下`v1.0.30.1`  
或者等过几天发`v1.0.31`再测试

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
