### ISSUE TITLE
能否添加指定界面语言的功能?

### ISSUE THREAD

**Issue by jitingcn** [nobody3u/V2RayGCon#18]
因为某些原因系统语言为英文,希望可以选择软件运行的界面语言

**Comment by nobody3u** [comment]
请帮忙测试反馈 [v1.0.31.1](https://github.com/nobody3u/V2RayGCon/releases/tag/v1.0.31.1)
记得测试前先备份数据。

位于选项在主窗口-`window`-`option`-`settings`-`language` 
因.net 4.0限制，设置完后要保存，然后重启才能生效。

**Comment by jitingcn** [comment]
感谢,功能正常
