### ISSUE TITLE
能否添加一个针对多个订阅的分组功能

### ISSUE THREAD

**Issue by redfrog999** [nobody3u/V2RayGCon#19]
现在的排列方式对有多个订阅，而且多个服务器有不同命名方式的查阅起来很费劲，因为记不住全部几十个服务器的名字，往下拉又是一大片，很不好找。能否实现这样的排列方式：

订阅组名称  服务器数量  最后更新时间

服务器一  服务器二  服务器三

另外，1.0.31 rc1.1 多开有点问题，我设置好了其中三个端口，有一个端口的服务器用其他v2ray客户端打开没问题，rc1.1连不上呢。已经滚回1.0.30了。非常感谢

**Comment by nobody3u** [comment]
多开的问题，你要记下复现步骤，不然很难排查
我翻查了`v1.0.31`的代码，全部都是界面方面的没涉及多开
所以如果有BUG，应该是以前就有，只是刚好你用那个版本的时候遇到了

服务器是无辜的，不要因为他来自一个不那么好看的订阅地址就岐视他。（开玩笑的）
其实我想知道的是为什么要按订阅源来分组？
不是应该按服务器的常用程度或者端口/速度/协议那些来分吗？
补充一下，分组是标记的任务。

找服务器那里我又不明白了，既然你记不住服务器的名字，那你想找的是什么？

然后更新时间，不用关心这个啊，想更新的时候就点下更新。
难道服务器用一个星期就丢掉不再用？

**Comment by redfrog999** [comment]
哈哈，是这样的，我搞了多个来源的多个订阅，这些服务器不少是众筹或者站长们捐献的，有些服务器短时间内变动蛮大的，或者说通联程度不是那么稳定，所以呢我得经常测试更新订阅后的这批服务器能不能用。现有软件的测速功能还是很不错的，就是打开界面之后看到乌压压一片的服务器，有点密集恐怖，就想能不能按照订阅组分开显示，这样看起来没有那么累眼，显示更新时间呢，也让我能及时知道哪些订阅组最近有了变动。纯粹是个人需求。

或者说有没有办法让我知道且标记当前的服务器是属于哪个订阅组的？现有的标记功能我已经用在标记通联状态了，再有个标记来识别订阅组就更好了。非常感谢。

关于多开问题我找到原因了，因为我还在用v2rayN这个软件，两个软件同时开启就会撞车：
先启动gcon再启动v2rayn肯定会让gcon弹出v2ray非正常终止的对话框；
先启动v2rayN再启动gcon不会弹出非正常终止的对话框，但是会影响通联状态，这时候多开就会出现gcon不能连上某个服务器，而v2rayn能连上的情况。

这是软件冲突吗？有没有修复的可能？这两个软件我都挺喜欢的。同时开启针对不同用途用起来很爽的。

**Comment by nobody3u** [comment]
那就不是闪退咯，吓死我了，还以为出了什么严重BUG
看v2rayn以前的issue，有人反馈过他启动的时候会杀死所有v2ray.exe的进程
于是是就弹`非正常终止`提示，这要v2rayn别那么暴力的杀进程才能解决

后一种情况，我能想到的有两种可能
1. 用了相同的端口，打开主窗口的日志，看下有没有错误提示信息
2. 系统代理冲突，v2rayn和v2raygcon轮流修改系统代理，导致其中一个用不了
其实我是不建议用`系统代理`模式，改用浏览器插件，切换代理更灵活

**Comment by redfrog999** [comment]
rc1.1版，我在gcon里边开开关关几个服务器几十次，就闪退了一次。1.0.31.2这个版本木有鸟。现在这个版本挺好的，我想解决的问题都解决了。

多开问题确实跟v2ray.exe进程有关，反正设置好启动次序，现在没问题了。或者重新在gcon里边再启动一次就好了。系统代理我就启用了v2rayN的，gcon的我没启用，所以应该不是这个导致的。

现在都OK啦，感谢感谢。

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
