### ISSUE TITLE
V2ray-core非正常终止

### ISSUE THREAD

**Issue by drw2005** [nobody3u/V2RayGCon#20]
上星期五还在正常使用，今天更新了下V2ray-core到3.45后，点击启动就出现V2ray-core非正常终止的错误提示，分别降低V2rayGCon和V2ray-core版本也不行，请问是何原因？

<img src="http://www.z4a.net/images/2018/10/02/QQ20181002092022.jpg" alt="QQ20181002092022.jpg" border="0" />

**Comment by nobody3u** [comment]
点`窗口`-`日志`看有什么提示?

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
