### ISSUE TITLE
再反馈一个问题：下载东西会产生很高的上传流量

### ISSUE THREAD

**Issue by redfrog999** [nobody3u/V2RayGCon#21]
也不知道这是不是个bug。1.0.31.2和1.0.32，不论是单开还是多开都会出现这个问题。我用的是联通。

前几天我在家用固网上网基本没注意这个问题。昨天和今天我用移动热点上网，就发现下载视频消耗的流量远比我预期的要高，我看了一部400M的视频产生了600M的流量，让我很纳闷，后来我用手机开热点，用台机来测试，才发现这个问题。

我用流量监测和速度监测软件来看就会发现，下载任何体量的软件或视频都会产生很高的上传速度，随即产生很大的上传流量。如果是固网还无所谓，用移动网络来上网看视频下东西就太吃亏了，流量消耗太快了。我同一个服务器用V2rayN就不会这样，下载基本不上传多少流量，基本就是几十kb。

作者能否帮忙测试看下，要能修一下就太好了。非常感谢。

**Comment by nobody3u** [comment]
分别测试了看视频和下载数据，没发现这现象。

测速软件用的是NetSpeedMonitor（NSM）
路由是指路由自带的流量统计

```
单位（MiB）
看视频      发送    接收   发送/接收比
--------------------------------------------
NSM          7      152        4%
路由          6      132        4%

下载软件   发送    接收   发送/接收比
--------------------------------------------
NSM        5      290      2%
路由       5      288      2%
```

所以你得检查下你的系统是不是有什么软件在偷跑流量  
或者会不会是统计软件数据出错了

**Comment by redfrog999** [comment]
感谢帮忙测试，原因找到了，用的翻墙软件有问题，换一个就好了。喵的，想不到啊，翻墙软件会出这种幺蛾子。现在一切正常了。

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
