### ISSUE TITLE
1.0.33的搜索功能废了？

### ISSUE THREAD

**Issue by redfrog999** [nobody3u/V2RayGCon#22]
测试了刚发的1.0.33，发现筛选过滤没任何作用，不论按照端口或者关键字搜索都没任何结果，1.0.32是可以实现的哇。期待下个版本修复。thx

**Comment by nobody3u** [comment]
试了一下，搜索能用啊，没发现问题。
暂时不知道什么原因。

**Comment by redfrog999** [comment]
我截图你看看呢。
第一张图，我的服务器的一部分
![snap1](https://user-images.githubusercontent.com/735748/46607858-19b81600-cb35-11e8-8262-9e50cebbfd13.jpg)

第二张图，用日本搜索什么都不显示呢？
![snap2](https://user-images.githubusercontent.com/735748/46607883-33f1f400-cb35-11e8-8371-d9f06e41d275.jpg)

**Comment by redfrog999** [comment]
第三张图，事实上是有一个日本节点的。
![snap3](https://user-images.githubusercontent.com/735748/46615571-13349900-cb4b-11e8-975a-35c551aa9313.jpg)


第四张图，1.0.32就是可以搜索到日本节点
![snap4](https://user-images.githubusercontent.com/735748/46615658-5d1d7f00-cb4b-11e8-9b3a-aa0eada46879.jpg)


能修复吗？thx

**Comment by nobody3u** [comment]
今天再试了次，还是没能重现这问题。目前不清楚出了什么问题。

**Comment by redfrog999** [comment]
1.0.34又可以用了，非常好，反应速度比1.0.32还要快。可以close这个issue了。thx

**Comment by nobody3u** [comment]
这只是巧合
我一直没能重现这个BUG，其实并没有修复
可能过几天又跳出来捣乱了

**Comment by redfrog999** [comment]
bug在1.0.34版到现在都没出来啦，很不错。不过有个建议，能不能实现在搜索的时候，对搜索出来的关键字变色或者高亮处理一下呢？

**Comment by redfrog999** [comment]
好哒，这个功能也不是刚需。thx

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
