### ISSUE TITLE
被WD查杀了

### ISSUE THREAD

**Issue by zanewayne78** [nobody3u/V2RayGCon#24]
![](https://i.loli.net/2018/10/24/5bd046303f240.png)
版本v1.1.0

**Comment by nobody3u** [comment]
有意思，微软Azure编译出来的东西被微软的Windows defender报病毒，哈哈哈。

我查了一下之前的Releases，发现是从添加PAC服务器开始报病毒。
我猜可能是之前复制的那份代码太多人用了（包括一些恶意软件也用了）所以误报了。
现在PAC服务器换成了[v2rayP](https://github.com/PoseidonM4A4/v2rayP)的代码，我这边试了下没报病毒了。

麻烦你也测试下，看还有没有报病毒吧：
https://github.com/nobody3u/V2RayGCon/releases/tag/1.1.0.8

注：
从10月份 v1.0.31 开始，Release都是由Azure编译自动发布的了
所以真正感染病毒的可能性很低，出这种情况通常是误报了

**Comment by zanewayne78** [comment]
没报了，只是订阅更新的时候能不能把已经剔除订阅的失效服务器删除？不然更新后列表越来越长了

**Comment by nobody3u** [comment]
但是这样就会把一些还能用，只是不在新订阅里面的服务器浪费了。

清理服务器的时候建议全选测速后，
`选择`-`全部服务器`-`选中测速超时`，
接着`服务器`-`删除服务器`-`删除选中`

或者给订阅起个比较容易区分的别名（不同来源可用相同别名），
例如：“订阅一”，再勾上下面的`标记`
此后更新的服务器都可以很方便的通过搜索框下拉列表选出
接着全选所有页面，删除选中

**Comment by zanewayne78** [comment]
感谢回复，只能多点几下了

**Comment by miy4mori** [comment]
似乎还是有问题，见动图。

![2018-10-30_10-51-22](https://user-images.githubusercontent.com/20637056/47692994-c0726c80-dc32-11e8-931f-fd2d7b814c97.gif)

**Comment by zanewayne78** [comment]
下了1.1.1版，没报毒，手动查也没，在线查只有一个引擎报Trojan.Crypt.CFI.Gen
http://r.virscan.org/language/zh-cn/report/3d689122e38cc2d6c0ce7657f99a0fe9

**Comment by zanewayne78** [comment]
![](https://i.loli.net/2018/10/30/5bd7df4adb1dd.png)
这是我的病毒库最新更新时间

**Comment by zanewayne78** [comment]
咦，过了一段时间又报毒了。。。

**Comment by nobody3u** [comment]
谢谢反馈，看来还有别的代码引发误报，只好一部分一部分慢慢删功能来测试了。

**Comment by snhun** [comment]
最新测试版今天又突然报毒了，昨天用都正常的。。
![qq 20181105105201](https://user-images.githubusercontent.com/5186603/47975463-e1cad100-e0e8-11e8-93a2-19a1da669861.png)

**Comment by nobody3u** [comment]
看来和设置系统代理时修改注册表有关
这次删除所有和注册表相关的代码试试

又得等一个星期看结果（摊手）

**Comment by snhun** [comment]
> 看来和设置系统代理时修改注册表有关
> 这次删除所有和注册表相关的代码试试
> 
> 又得等一个星期看结果（摊手）

哈哈，辛苦了。

**Comment by snhun** [comment]
![qq 20181119094207](https://user-images.githubusercontent.com/5186603/48690357-1cfcf200-ec09-11e8-86a0-ccffb70eca5a.png)

**Comment by nobody3u** [comment]
这两周defender没理我了，不过要是他再报病毒，我也没什么代码可以删了，只能让他报了。
所以关闭这个issue啦。

因报病毒问题搜到这个issue的小伙伴，请看 [关于杀毒软件报病毒问题说明](https://github.com/nobody3u/V2RayGCon/wiki/%E5%85%B3%E4%BA%8E%E6%9D%80%E6%AF%92%E8%BD%AF%E4%BB%B6%E6%8A%A5%E7%97%85%E6%AF%92%E9%97%AE%E9%A2%98%E8%AF%B4%E6%98%8E)  
用还是不用自己决定了。
