### ISSUE TITLE
添加v4格式好像无法代理

### ISSUE THREAD

**Issue by snhun** [nobody3u/V2RayGCon#26]
原来的格式可以正常代理，不知是否个例

**Comment by nobody3u** [comment]
初步试了下发现`分流CN网站`那个选项和4.0的格式不兼容。
如果你的不是这个问题，那么需要提供一下详细信息才能排查原因。
比如出问题的配置文件，以及不能代理时选了哪些选项。

**Comment by snhun** [comment]
> 初步试了下发现`分流CN网站`那个选项和4.0的格式不兼容。
> 如果你的不是这个问题，那么需要提供一下详细信息才能排查原因。
> 比如出问题的配置文件，以及不能代理时选了哪些选项。

对了，之前那个测试版跟这个版本，来回试了好久，确认是'分流CN'网站问题。

**Comment by nobody3u** [comment]
好的。下个版本将修复这个问题，谢谢反馈。
