### ISSUE TITLE
v1.1.2 portable 版，点击工具栏的齿轮图标，弹出的设置窗口自动跑到后面去了。

### ISSUE THREAD

**Issue by neatgz** [nobody3u/V2RayGCon#27]
Win10 1803 x64 with all updates
vgc v1.1.2
如图所示：
点击 `齿轮按钮` 时，弹出窗口跑到后台去了。
点击 `菜单栏` `选项` 时，无此问题。
![snipaste_2018-11-14_18-49-49](https://user-images.githubusercontent.com/22790906/48478108-4fd86c00-e83e-11e8-8b9a-fd0480e30793.png)

**Comment by nobody3u** [comment]
谢谢反馈，将在下个版本修复。
