### ISSUE TITLE
可否考虑讲配置文件保存在V2RayGCon.exe文件夹下（便携化）

### ISSUE THREAD

**Issue by OneWizard** [nobody3u/V2RayGCon#3]
RT, 重装系统后发现配置全丢，后来发现原来是在AppData\Local下
如果可以，希望能保存在V2RayGCon.exe同级的地方或者建个config文件夹之类的
顺带添加不改变当前系统代理模式（多代理软件冲突）

**Comment by nobody3u** [comment]
写这个程序的时候我是用.net自带的properties。
你不说我还真不知道原来.net偷偷把数据存在那里:satisfied:

配置建议通过导出v2ray链接来保存。
就是主窗口中 `操作` -> `复制全部服务器` -> `v2ray://...`，然后粘贴到记事本。
导入的时候记事本全选复制然后点 `剪切板导入` 。
这样做的好处是不依赖于客户端，就算将来客户端的设置怎么变，服务器的配置都能用。
甚至没客户端的时候也可以打命令解base64得出config.json。
不过这个用法有点绕，看来有必要写在wiki里。

谢谢提出系统代理模的问题，我没考虑到这种情况。在v1.0.4中改了设置系统代理的逻辑。
现在如果V2RayGCon修改过系统代理，那么退出程序的时候会清除掉，否则不清除。
