### ISSUE TITLE
v1.1.2 版本 勾选v4版本 使用IPv6地址 插入内容 bug

### ISSUE THREAD

**Issue by Dorl121** [nobody3u/V2RayGCon#30]
客户端 如果IP类型是IPv6，插入失败，会显示“127.0.0.1：1080”

**Comment by nobody3u** [comment]
对IPv6不是很熟悉，直接把IPv6当网址处理了。
请测试 [v1.1.2.4](https://github.com/nobody3u/V2RayGCon/releases/tag/1.1.2.4)，看有写错的地方。

**Comment by Dorl121** [comment]
OK 没问题了 感谢
