### ISSUE TITLE
v 1.1.3

### ISSUE THREAD

**Issue by bjwanghao** [nobody3u/V2RayGCon#31]
全局代理  不能用了

**Comment by nobody3u** [comment]
是的。

全局代理需要修改注册表。从issue #24里面的各种尝试结果来看，任何修改注册表的代码都会触发windows defender报病毒。所以v1.1.3起删除这些功能。现在需要手动修改系统的代理设置，才能开启全局代理。而PAC功能需要自己编译release版。

突然有个想法，一会试下同时发两个版本，一个包含PAC功能，一个不包含，看下个星期是一起报病毒还是分别对待。

**Comment by nobody3u** [comment]
和注册表具体键值位置无关，凡是修改注册表的行为都引发defender报病毒。
很久没看v2rayN的代码了，我也不太清楚他是怎么处理的。

不过其实重点并不是怎么处理，而是有没有被defender盯上。
其实修改注册表的代码从很久很久以前就有了。
可能是下载这个软件的人渐渐多起来，然后defender突然就发飚了。
比如v1.1.1.7只是在v1.1.1.6的基础上删除了一些代码，并没其他改动。
神奇的是defender只对很多人下载的1.1.1.7报病毒，而没几个人下载的1.1.1.6却不报 。
报病毒这个问题，只能看defender心情啦，我已经没什么能做的了。

刚才修改了v1.1.3的发布内容，添加一个带ProxySetter功能的zip包。
不过，按之前的情况推测，下个星期是肯定会报病毒。
所以根据自己情况选择下载哪个版本啦。

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
