### ISSUE TITLE
1.1.3长时间打开日志程序会卡死

### ISSUE THREAD

**Issue by winds365** [nobody3u/V2RayGCon#32]
用sstap接本地socks5玩日服LOL，v2rayGcon打开日志的情况下，玩10分钟左右v2rayGcon主程序卡死消失

**Comment by nobody3u** [comment]
请测试 [v1.1.3.3](https://github.com/nobody3u/V2RayGCon/releases/tag/1.1.3.3)  

p.s.
需要长时间或高并发记录日志时，建议配置log分节，使用日志文件。
