### ISSUE TITLE
PAC模式怎么都不成功，求个配置细节啊

### ISSUE THREAD

**Issue by maryjeck** [nobody3u/V2RayGCon#33]
如题，

**Comment by nobody3u** [comment]
PAC模式自带了一份PAC，不需要配置。
ProxySetter的PAC分页是在默认PAC配置不够用做调整时使用的。

开启方法是 代理模式 选 PAC，勾上后面的 自动，然后 保存。
在主窗口中点你想用的服务器的`>`按钮，重启一下服务器。
这时日志窗口应该可以看到相应提示。

点ProxySetter-常规-状态 里面右上角的“在浏览器打开调试页面”按钮，
可以查询某个网址是走代理还是直连（只是大概，不是很准的）。

**Comment by maryjeck** [comment]
GOOGLE 怎么设置都是direct，btw：v2ray-core 用的socks模式
