### ISSUE TITLE
Bitdefender报毒

### ISSUE THREAD

**Issue by KirbyKFC** [nobody3u/V2RayGCon#37]
版本: v1.1.4

lite和defender-test报Gen:Variant.Ursu.335444
full报Gen:Variant.Jhonnie.140394

用VirusTotal扫了一下，基本上BD系的都报了。
[VirusTotal扫描结果](https://www.virustotal.com/#/file/e4dcd49479fa413e89f486e438813472acfe0f1340c5928059888f984de029f4/detection)

**Comment by nobody3u** [comment]
谢谢反馈！
从issue #24 开始已经1个多月了，我已经没什么可以做的了。他们爱报就报吧。

我做了以下几项来尽可能保证各位下载到的软件安全：
1. 大概从v1.0.31开始，编译、打包、发布都由微软Azure的Pipeline服务器完成
2. 程序用到的NuGet包都选下载人数最多的
用到的包列表如下：
```bash
  Autoupdater.NET.Official
  DotNetZip
  jacobslusser.ScintillaNET
  Newtonsoft.Json
  ZXing.Net
```
3. box（开箱即用版）的v2ray-core是直接下载不解压，在Azure服务器打包时才解压和打包
有考究精神的小伙伴可以查之前的commit
看v2ray-windows-32.zip的校验和是否和v2ray官网公布的的相符

除了上面几项，剩下的就是代码了，我不敢说自己的代码100%安全  
毕竟我不是安全专家，我只能保证自己没特意去写恶意代码  

然后针对杀毒软件，我分别向windows defender和卡巴发了报告
卡巴一直没报病毒，我发的是怀疑自己程序有病毒的报告，不过除了机器人回复以外没其他回复  
微软有报病毒，我提交的是误报申请，然后回复了保持原判  
其实他们根本就不会理这些小软件  

所以总的来说，这个报病毒大概是误报（我不是安全专家，不敢说肯定是误报）
如果介意，请不要使用
如果不介意，请在杀毒软件里面加例外
或者自己下载源码稍改一下再编译，杀毒软件就不会再报病毒

**Comment by nobody3u** [comment]
因报病毒问题搜到这个issue的小伙伴，请看 [关于杀毒软件报病毒问题说明](https://github.com/nobody3u/V2RayGCon/wiki/%E5%85%B3%E4%BA%8E%E6%9D%80%E6%AF%92%E8%BD%AF%E4%BB%B6%E6%8A%A5%E7%97%85%E6%AF%92%E9%97%AE%E9%A2%98%E8%AF%B4%E6%98%8E)。  
用还是不用自己决定了。  
先关闭issue啦。
