### ISSUE TITLE
pac模式没有v2rayN处理的好，从来没有成功过。

### ISSUE THREAD

**Issue by maryjeck** [nobody3u/V2RayGCon#38]
pac模式没有v2rayN处理的好，从来没有成功过。

**Comment by nobody3u** [comment]
[ProxySetter使用说明](https://github.com/nobody3u/V2RayGCon/wiki/ProxySetter) 
相关 issue #33 

请详细描述你遇到的问题以及操作步骤.

**Comment by nobody3u** [comment]
你在 #33 回复但没 Reopen 所以一直没看到你的回复
> GOOGLE 怎么设置都是direct，btw：v2ray-core 用的socks模式

你没详说ProxySetter的各参数和运行状态
所以我假设你用的是使用说明里的设置
并且状态中显示：PAC服务器运行中
然后direct指的是PAC debugger里的Result

这个是正常情况，因为默认pac中的url列表是带后缀的
所以输入google.com才会匹配到，而google没在他的列表里面就显示direct啦
不过这应该不影响PAC模式正常使用，所以估计有其他因素影响
但是上面做太多假设了，还是等你回复再定了

**Comment by maryjeck** [comment]
代理模式：pac
代理端口：1080
pac端口：3000
pac模式：白名单
pac协议：socks

Keyword:google.com
Result:SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT

**Comment by maryjeck** [comment]
> 你在 #33 回复但没 Reopen 所以一直没看到你的回复
> 
> > GOOGLE 怎么设置都是direct，btw：v2ray-core 用的socks模式
> 
> 你没详说ProxySetter的各参数和运行状态
> 所以我假设你用的是使用说明里的设置
> 并且状态中显示：PAC服务器运行中
> 然后direct指的是PAC debugger里的Result
> 
> 这个是正常情况，因为默认pac中的url列表是带后缀的
> 所以输入google.com才会匹配到，而google没在他的列表里面就显示direct啦
> 不过这应该不影响PAC模式正常使用，所以估计有其他因素影响
> 但是上面做太多假设了，还是等你回复再定了

代理模式：pac
代理端口：1080
pac端口：3000
pac模式：白名单
pac协议：socks

Keyword:google.com
Result:SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT

**Comment by nobody3u** [comment]
你可以打开debugger页面，说明pac服务器可以正常运行了。
然后查询也返回了sock5开头的结果，说明pac文件工作也正常。
还需要看下右边状态那部分，最后一行是不是像这样（后面的随机字符串省略）：
`http://localhost:3000/pac/?t=.....`
如果不是，说明有其他软件修改了系统代理，要手动修改系统的代理设置。
如果是，那么这时打开chrome，代理模式选“系统代理”应该可以访问网页了。

如果你用的是IE（或者同类型）浏览器，将不能使用，主要有2个原因：
一个是IE不支持SOCKS代理，只支持HTTP代理
另一个是刚才排查的时候发现个小BUG，将在下个版本将修复

**Comment by maryjeck** [comment]
v2ray.com/core/proxy/socks: unknown Socks version: 67

**Comment by nobody3u** [comment]
`unknown Socks version: 67` 
在v2ray设置为socks协议，而浏览器（或者其他使用代理的软件）设置为HTTP协议时会出现这个提示。

**Comment by nobody3u** [comment]
v1.1.5应该没这个问题了，先关issue了。
