### ISSUE TITLE
便携模式BUG

### ISSUE THREAD

**Issue by ccboxes** [nobody3u/V2RayGCon#40]
发现开启便携模式后，使用快捷方式运行会导致程序将便携方式所在目录认定为自身所在目录，进而无法读取配置。

**Comment by ccboxes** [comment]
解决了，原来是快捷方式中起始位置未设置导致的。

**Comment by nobody3u** [comment]
谢谢你的经验，将把这条写进问题和解决方法的wiki中。

**Comment by nobody3u** [comment]
nobody 使用了:seven:天无理由关issue特权:zzz:
