### ISSUE TITLE
统计(v4)的问题

### ISSUE THREAD

**Issue by Neomanbeta** [nobody3u/V2RayGCon#41]
不知道是不是BUG，但是我这里可以重现，系统win10 1809。
便携模式，打开统计(V4)以后，socks模式无法开启本地端口，比如我设置的是1080，关闭以后一切正常。

**Comment by nobody3u** [comment]
估计是因为配置冲突所以没法使用

因v2ray-core的设计问题，开启API功能要在原配置基础上注入很多配置
这很容易和原配置发生冲突，所以流量统计十分娇情，配置有点不合胃口就用不了
要是v2ray-core可以通过命令行来开启、关闭API功能就会好很多

`统计(v4)`功能只能用在v4格式的配置中
即只有in(out)bounds没有in(out)bound(Detour)
routing下面是直接跟rules而不是routing.settings.rules
第一个inbounds中的tag还必须是agentin

简单点来说就是，可以用在选项窗口中勾了`优先使用v4格式`之后导入的vmess:// ... 链接
而手动修改过的，或者使用了旧格式的配置则很可能出各种问题

下面是实现原理，有助于自行排查问题，不感兴趣可以不看。
V2RayGCon如果勾了`统计(V4)`选项，启动新服务器时
会在服务器原配置的基础上[import](https://github.com/nobody3u/V2RayGCon/wiki/Import%EF%BC%88%E5%AF%BC%E5%85%A5%E6%A8%A1%E6%9D%BF%EF%BC%89)一个[stats.json](https://raw.githubusercontent.com/nobody3u/VGCTpl/master/Template/V4/stats.json)(流量统计模板)
其中inbounds.port自动生成
然后把原配置inbounds[0]的tag设置为"agentin"
查询的时候会使用像下面这样的命令：
```
v2ctl api --server="127.0.0.1:1090" StatsService.GetStats "name: """"inbound>>>agentin>>>traffic>>>downlink"""" reset: true"
```

**Comment by Neomanbeta** [comment]
ok，那我试试改成v4的模式再开启这个。
