### ISSUE TITLE
如何设置自定义PAC

### ISSUE THREAD

**Issue by winds365** [nobody3u/V2RayGCon#43]
如何设置自定义PAC
例如https://github.com/breakwa11/gfw_whitelist
这里的PAC要怎么弄才能用
是否把PAC地址的localhost改为127.0.0.1
建议软件退出和关机都自动清除代理设置
1.1.4和1.1.5都不会自动清除代理设置
刚又试了下，是关机的时候不会自动清除代理设置
电脑重启代理设置还在，软件启动再退出恢复之前的代理设置
以前v2rayN也有这样的BUG，某次更新修复了

**Comment by nobody3u** [comment]
关机时恢复原系统代理的功能是有的
可能我又不知道在哪里写了个BUG，导致恢复功能失效了，这个要慢慢查了

刚才测试自定义PAC的时候发现有2个BUG，所以还是等下周v1.1.6再用这个功能吧
如果想在`v1.1.5`中测试自定义PAC功能要注意以下两点：
1.选完PAC文件保存后，要用文本编辑器修改下pac文件，加个空格什么的然后保存，这样才会触发缓存刷新
2.修改完PAC文件或者切换服务器后，要重启下chrome浏览器才生效，没测试IE不知道会怎么样

**Comment by nobody3u** [comment]
gfw_whitelist的PAC只试了下whitelist.pac
需要把`var wall_proxy = ...`那行改成像下面那样（只对socks服务器有效）
```
var cAddr = customSettings.ip + ":" + customSettings.port + ";";
var wall_proxy = "SOCKS5 " + cAddr + " SOCKS " + cAddr;
```
http服务器或者其他PAC文件，根据上面的示例自行修改吧，不一一列举了

**Comment by winds365** [comment]
我发现一个奇怪的现象，软件运行久了会把baidu解析到国外去
初步猜测应该就pac地址中的localhost解析到了本机的v6地址[::1]
我是win10系统，默认开启v6协议，路由不支持

**Comment by nobody3u** [comment]
localhost只在浏览器下载、读取pac文件时才会用到
做pac查询、解释时用的是127.0.0.1（除了自定义PAC）
我看过的几个常见的PAC内部都是用IPv4地址，没见到有IPv6的
所以应该不会是这两个的问题
不过具体是什么原因就不清楚了
