### ISSUE TITLE
v2rayN.exe能用，但用你制作的不能用

### ISSUE THREAD

**Issue by ntgeralt** [nobody3u/V2RayGCon#46]
今天尝尝鲜，先试下你的新客户端。发现怎么都用不了。先是lite，点击自动下载了core，然后导入v2rayN.exe生成的vmess（服务端为tls ws），找了许久才找到需要启动服务器。启动了，发现日志无任何反应，无法上google

然后尝试了box版本，一打开程序，发现你依然提示下载core。当然我直接导入vmess后依然无法使用。服务器on下打开chrome访问google，依然无响应，日志无任何变化。

另外测试好像只测延时。我ping服务器是100ms，测延时总显示600ms+...

一些问题，在此反馈下

**Comment by winds365** [comment]
这个软件上手难度是5星
如果把v2rayN的比作是ss
那么这个软件就是v2ray
如果你想要系统代理的话
要加上ProxySetter插件
要不然只能通过其他软件调用，比如SSTap

**Comment by ntgeralt** [comment]
> 这个软件上手难度是5星
> 如果把v2rayN的比作是ss
> 那么这个软件就是v2ray
> 如果你想要系统代理的话
> 要加上ProxySetter插件
> 要不然只能通过其他软件调用，比如SSTap

那就是回到2016年刚接触v2raycore，chrome配合Proxy SwitchySharp插件的年代了。不知道该说geek还是说返祖

**Comment by nobody3u** [comment]
测速的延时高是因为那不是简单的ping值，而是服务器可用性测试
那个时间是访问google.com消耗的时间
所以600ms非常快了，我通常是2000ms附近
按你描述的情况来看，已经正常运行了
再设置一下系统代理（默认是127.0.0.1:1080）就可以
box版不需要再下载core，看来引导界面用词有点不当，引起误会。

二楼说的ProxySetter是这个软件full版和box版自带的插件，不需要另外安装。
用法在[选项-插件](https://github.com/nobody3u/V2RayGCon/wiki/%E9%80%89%E9%A1%B9%E7%AA%97%E5%8F%A3#%E6%8F%92%E4%BB%B6v112)和[ProxySetter](https://github.com/nobody3u/V2RayGCon/wiki/ProxySetter)里有详细说明

**Comment by nobody3u** [comment]
系统代理功能设计得这么复杂，其实要从v1.0.34-v1.1.2那段黑历史说起
一开始这个功能是和这个软件整合在一起，点下菜单就可以用的
然而当这个软件习得PAC绝技不久之后，windows defender突然跳出来说这软件有毒
人家是大boss，不管你是不是真的有毒，反正他说你有就是有
跟他讲道理，提交误报申请根本不理，没办法只好自断双臂，不，是自删功能
于是在v1.1.1.6到v1.1.1.11那段黑暗的日子里面
pac和全局代理功能被移进移出修改过好多次
最可怜的是v1.1.1.11被删到真的变成一根光棍，只剩个编辑器了
（剧透一下v1.1.1.11其实就是lite版的前身)
最黑暗应当数v1.1.2，那时pac功能变成了地下党
完全移出这个项目，转移到了VgcPlugins项目中
当时要启用pac功能得自己下载dll，自己解压到plugins目录
（真心感谢那个黑暗的年代还在用这个软件的人）
到了v1.1.3其实我已经想放弃，准备不管他报不报病毒都pac加回主项目里面算了
然而这时却出现了一点转机，windows defender开始松口，不追着这软件咬了
但是，bitdefender又跳了出来，说这软件是病毒
其实pac功能的主要代码一直都没怎么变，变的只是那些的杀毒软件
从issue #24到v1.1.3已经一个多月了，我也累了，只想专心添功能，不想再理那些杀毒软件
所以后面就一直沿用了v1.1.3的结构没再改了
那帮杀毒软件喜欢怎么报就怎么报吧

**Comment by ntgeralt** [comment]
我长期SSCap和v2rayN两个换着用，他们PAC模式都很好很正常。两款软件下载量都数十万了，他们在我电脑里火绒也没报毒。我觉得你不必理会小众群体报毒，致力于把软件做顺手，或做成你想要的样子，就好了

**Comment by nobody3u** [comment]
微软亲儿子还是要特殊关照一下，毕竟用户基数不小。
同时从下载统计来看还有人需要lite版，
所以这个软件短时间内将继续按目前结构发展下去。
