### ISSUE TITLE
win7下激活服务器连接后，报v2ray-core非正常终止。

### ISSUE THREAD

**Issue by wwxs972** [nobody3u/V2RayGCon#7]
正常下载安装，自动下载v2ray-core，配置服务器后激活，报v2ray-core非正常终止弹出框

**Comment by nobody3u** [comment]
抱歉，在虚拟机试了下，没能复现这个错误。

这个提示可能和下面几项相关：

#### 1.配置有误
日志窗口大概会显示这样的信息
```
V2Ray v3.36 (die Commanderin) 20180823
A unified platform for anti-censorship.
Main: failed to read config file: stdin: 
> Main|Json: failed to execute v2ctl to convert config file. 
> Command|Platform|CtlCmd: failed to execute 
v2ctl: Ext|Tools|Conf|Command: failed to parse json config 
> Ext|Tools|Conf|Serial: failed to parse json config 
> Ext|Tools|Conf: Api tag can't be empty.

 > exit status -1


v2ray-core 已关闭!
```
解决办法：根据提示信息检查修改配置

#### 2.下载的v2ray-core和系统不匹配
比如32位系统下载了64位的v2ray-core
解决办法：重新下载，通常32位的core兼容性较好。

#### 3.其他软件杀死了v2ray.exe
解决办法：关掉不必要的软件再激活，逐个排查。
  
  
如果上面的情况都不是，暂时我也没想到什么问题。
欢迎继续反馈。

**Comment by wwxs972** [comment]
我的情况是之前安装了v2rayn，64位win7下使用的是v2ray-core32位，使用 一切正常。下载了 v2raycc准备试用，配置连接后出现错误 。今天又操作了下，错误造成原v2rayn报错。删除所有目录 ，全部 下载新建目录，原v2rayn使用正常。下载64位v2raycore也正常。v2raycc手工下载v2raycore64位复制到同一目录， 打开v2raycc正常。配置连接后，配置测试窗口启动服务器又出现v2ray非正常关闭。

**Comment by nobody3u** [comment]
弹出这个错误的时候，配置测试器中显示什么信息？
（可ctrl+a ctrl+c复制）

**Comment by wwxs972** [comment]
V2Ray v3.26 (die Commanderin) 20180614
A unified platform for anti-censorship.
Failed to start App|Proxyman|Inbound: failed to listen TCP on 1081 > Transport|Internet: failed to listen on address: 127.0.0.1:1081 > listen tcp 127.0.0.1:1081: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.


v2ray-core 已关闭!

**Comment by wwxs972** [comment]
v2rayn下1080正常使用。切换到v2raycg，不开启配置测试，不报错，但不能正常翻墙。

**Comment by nobody3u** [comment]
以前v2rayn因为用了privoxy默认是开2个相连的端口。
现在不知道改了没有。
你正好都设成了他用的端口。。。

不能翻墙的有很多可能，打开日志窗口注意输出信息，看提示是什么问题。

**Comment by wwxs972** [comment]
日志窗口里没有任何信息

**Comment by wwxs972** [comment]
我关闭了v2rayn，应该不涉及到占用端口吧。查了进程，没有关于v2ray或v2ray的使用进程。

**Comment by nobody3u** [comment]
日志窗口是不会存档的，所以要先打开日志窗口，再双击激活服务器才会有信息。
还是报端口占用，非正常关闭吗？

**Comment by wwxs972** [comment]
又试了下，点击代理设置系统代理，google的chrome可以正常访问，firefox浏览器暂时还不行。在配置测试里面启动，还是报1080端口占用，非正常终止 。退出关闭配置测试，chrome还可以正常访问。

**Comment by nobody3u** [comment]
非正常终止是因为主窗口和配置测试器是相互独立的,
所以你启动了2个v2ray-core，
他们一起抢1080端口，导致后启动的那个退出。

系统代理的那个选项只是临时的，每次关机/退出软件都会清除，
所以你最好给浏览器装个代理切换插件

可以参考这个教程，
https://glorystar.me/archives/chrome-use-switchyomega-autoproxy.html
到 `配置智能翻墙 照例有一个说明 看下（也可跳过）` 这步就可以，
后面的步骤不需要。
