### ISSUE TITLE
能加一下服务器订阅功能吗?

### ISSUE THREAD

**Issue by lukemin** [nobody3u/V2RayGCon#8]
能加一下服务器订阅功能吗?

**Comment by nobody3u** [comment]
你能提供几个订阅的url做测试吗？
同时这个功能估计要过一段时间才能完成。

**Comment by nobody3u** [comment]
[`V2RayGCon v1.0.21`](https://github.com/nobody3u/V2RayGCon/releases/tag/v1.0.21)

**Comment by nobody3u** [comment]
终于改好，迎测试反馈。

[V2RayGCon v1.0.21](https://github.com/nobody3u/V2RayGCon/releases/tag/v1.0.21)

**Comment by lukemin** [comment]
没找到地方：）

**Comment by nobody3u** [comment]
先用一段时间再定吧，这个很容易修改。
选项那个窗口以后还会增加功能，
增加功能之后就会觉得放那“合理”一点。

用法：[选项窗口](https://github.com/nobody3u/V2RayGCon/wiki/%E9%80%89%E9%A1%B9%E7%AA%97%E5%8F%A3)
