### ISSUE TITLE
开机启动会清除系统代理设置

### ISSUE THREAD

**Issue by mmyz1234** [nobody3u/V2RayGCon#9]
系统：Win10
V2RayGCon版本：1.0.27
问题描述：V2RayGCon开机启动，从软件中设为系统代理。当电脑，重启后，系统代理设置会自动被清除掉，导致无法代理。
暂时解决办法：从软件中清除系统代理设置，然后在Win10系统的设置>网络和Internet>代理>手动设置代理，启用使用代理服务器，设置好地址和端口信息，保存。经测试，这样设置的话重启电脑系统代理设置正常，V2RayGCon开机自启代理正常。

**Comment by nobody3u** [comment]
这个是预期行为。这样设置的主要目的是防呆。

假设有个不太懂电脑的用户，试用这软件时开了系统代理，然后觉得这软件不好用就没再用。
如果软件退出时不清理，那个用户将无法使用网络。
而如果每次都清理，最多就不能访问google，不会影响其他网站的访问。

懂电脑的用户，可以像你那样自行设置一下代理，或者用浏览器插件。

目前的`系统代理`的设定是如果使用软件过程中选过，
软件退出时会清除，否则保持系统原样。

**Comment by mmyz1234** [comment]
> 这个是预期行为。这样设置的主要目的是防呆。
> 
> 假设有个不太懂电脑的用户，试用这软件时开了系统代理，然后觉得这软件不好用就没再用。
> 如果软件退出时不清理，那个用户将无法使用网络。
> 而如果每次都清理，最多就不能访问google，不会影响其他网站的访问。
> 
> 懂电脑的用户，可以像你那样自行设置一下代理，或者用浏览器插件。
> 
> 目前的`系统代理`的设定是如果使用软件过程中选过，
> 软件退出时会清除，否则保持系统原样。

是否可以增加选项，实现当启动代理服务后自动设为系统代理，而关闭服务或退出软件则自动清除。

**Comment by nobody3u** [comment]
思考了一下，多个服务器的时候跟踪服务器会比较麻烦。
所以偷了下懒，现在把系统代理的设置规则修改为：

1.关闭软件时：
恢复为系统原来的设定 

2.开启软件时：
如果上次没设置系统代理则保持系统原状不作处理
否则设为上次设定的代理地址
